### ISSUE TITLE
Is DTLS Mandatory

### ISSUE THREAD

**Issue by drasko** [gotthardp/gen_coap#12]
Looks like DTLS is mandatory - at least I can not find an easy way to turn it off.

I would like to test and understand how it all works without DTLS first, then add it after.

Also, on Debian there is not Erlnag 19.2 yet.

**Comment by Xdeon** [comment]
Though not related to this issue, but just FYI that Erlang 19.2 and newer can be downloaded from
[erlang-solutions](https://www.erlang-solutions.com/resources/download.html).

**Comment by gotthardp** [comment]
DTLS is not mandatory. If DTLS is not requested by using `coaps://`, or `start_dtls` the system shall be usable also on lower Erlangs. Is it not?

**Comment by drasko** [comment]
Thanks, I'll test tonight and let you know.

**Comment by drasko** [comment]
Seems to be working OK. I will close the issue.
