### ISSUE TITLE
Timeout for unreachable host

### ISSUE THREAD

**Issue by tpitale** [gotthardp/gen_coap#19]
`coap_client:request(get, "coap://somehost/api")`

This never times out if the host is unreachable. I see that `coap_transport` has mention of `ACK_TIMEOUT` so I'm not sure why this won't error.

Any help/ideas would be much appreciated, thanks!

**Comment by gotthardp** [comment]
Hi. There appears to be no timeout in the coap_client. That is of course wrong.

**Comment by gotthardp** [comment]
Hello again. I just made fix. Default timeout is now 30s and it can be modified by a new coap_client:request parameter.

**Comment by tpitale** [comment]
Thank you!
